name: piis

services:
  db:
    image: postgres:17-alpine
    container_name: uis_postgres
    restart: always
    environment:
      POSTGRES_DB: uis_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: uis_password123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - uis_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: uis_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:uis_password123@db:5432/uis_db
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=480
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - uis_network
    volumes:
      - ./backend:/app

volumes:
  pgdata:

networks:
  uis_network:
    driver: bridge
